/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 packages/web/public/assets/assets/chair.glb -o packages/web/src/components/ChairModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['chairDesk(Clone)']: THREE.Mesh
    Mesh_chair: THREE.Mesh
    Mesh_chair_1: THREE.Mesh
  }
  materials: {
    metalMedium: THREE.MeshStandardMaterial
    carpet: THREE.MeshStandardMaterial
  }
}

export function ChairModel(props: any) {
  const { nodes, materials } = useGLTF('/assets/chair.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['chairDesk(Clone)'].geometry} material={materials.metalMedium}>
        <group position={[0.167, 0.19, -0.16]}>
          <mesh geometry={nodes.Mesh_chair.geometry} material={materials.carpet} />
          <mesh geometry={nodes.Mesh_chair_1.geometry} material={materials.metalMedium} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/assets/chair.glb')
