/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 packages/web/public/assets/character.glb -o packages/web/src/components/CharacterModel.tsx 
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useMemo } from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations, Html } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'
import { AgentState } from '../App'

type ActionName = 'static' | 'idle' | 'walk' | 'sprint' | 'jump' | 'fall' | 'crouch' | 'sit' | 'drive' | 'die' | 'pick-up' | 'emote-yes' | 'emote-no' | 'holding-right' | 'holding-left' | 'holding-both' | 'holding-right-shoot' | 'holding-left-shoot' | 'holding-both-shoot' | 'attack-melee-right' | 'attack-melee-left' | 'attack-kick-right' | 'attack-kick-left' | 'interact-right' | 'interact-left' | 'wheelchair-sit' | 'wheelchair-look-left' | 'wheelchair-look-right' | 'wheelchair-move-forward' | 'wheelchair-move-back' | 'wheelchair-move-left' | 'wheelchair-move-right'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    ['body-mesh']: THREE.SkinnedMesh
    ['head-mesh']: THREE.SkinnedMesh
    root: THREE.Bone
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function CharacterModel({ state, tool, isSubagent, ...props }: any & { state: AgentState, tool?: string, isSubagent?: boolean }) {
  const group = useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/assets/character.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  // Map state to animation
  useEffect(() => {
    let animName: ActionName = 'sit'
    
    if (state === 'working') {
      animName = 'sit' // Will manually wiggle arms in useFrame
    } else if (state === 'thinking') {
      animName = 'sit'
    } else if (state === 'waiting_on_user') {
      animName = 'interact-right'
    } else if (state === 'error') {
      animName = 'crouch'
    } else if (state === 'idle') {
      animName = 'sit'
    }

    // if subagent is walking over, we use 'walk', but let's stick to simple state maps first
    
    // Play animation
    const action = actions[animName]
    if (action) {
      action.reset().fadeIn(0.2).play()
      return () => {
        action.fadeOut(0.2)
      }
    }
  }, [state, actions])

  const armRight = nodes.root.getObjectByName('arm-right') as THREE.Bone
  const armLeft = nodes.root.getObjectByName('arm-left') as THREE.Bone

  useFrame((stateCtx) => {
    if (state === 'working' && armRight && armLeft) {
      // Simulate typing
      armRight.rotation.x = Math.sin(stateCtx.clock.elapsedTime * 20) * 0.2
      armLeft.rotation.x = Math.sin(stateCtx.clock.elapsedTime * 20 + Math.PI) * 0.2
      stateCtx.invalidate() // keep frameloop active
    }
  })

  // Set colors based on state to give the character a tint or just leave natural
  useEffect(() => {
    // We could tint the material, but for now let's just use the default colormap
  }, [state])

  const scale = isSubagent ? 0.7 : 1.0;

  return (
    <group ref={group} {...props} scale={scale} dispose={null}>
      <group name="character-male-a" position={[0, -0.4, 0]}>
        <group name="character-male-a_1">
          <primitive object={nodes.root} />
          <skinnedMesh name="body-mesh" geometry={nodes['body-mesh'].geometry} material={materials.colormap} skeleton={nodes['body-mesh'].skeleton} />
          <skinnedMesh name="head-mesh" geometry={nodes['head-mesh'].geometry} material={materials.colormap} skeleton={nodes['head-mesh'].skeleton} />
        </group>
      </group>

      {/* Tool Label */}
      {state === "working" && tool && (
        <Html position={[0, 1.5, 0]} center>
          <div style={{
            background: "rgba(59, 130, 246, 0.9)",
            color: "white",
            padding: "4px 8px",
            borderRadius: "6px",
            fontSize: "12px",
            fontWeight: "bold",
            whiteSpace: "nowrap",
            pointerEvents: "none",
            boxShadow: "0 2px 5px rgba(0,0,0,0.2)"
          }}>
            ⚡ {tool}
          </div>
        </Html>
      )}

      {/* Thinking Bubble */}
      {state === "thinking" && (
        <Html position={[0, 1.5, 0]} center>
          <div style={{
            background: "rgba(168, 85, 247, 0.9)",
            color: "white",
            padding: "4px 8px",
            borderRadius: "10px",
            fontSize: "16px",
            whiteSpace: "nowrap",
            pointerEvents: "none"
          }}>
            🤔...
          </div>
        </Html>
      )}

      {/* Waiting Marker */}
      {state === "waiting_on_user" && (
        <Html position={[0, 1.5, 0]} center>
          <div className="waiting-marker" style={{
            background: "rgba(245, 158, 11, 0.9)",
            color: "white",
            padding: "4px 8px",
            borderRadius: "6px",
            fontSize: "14px",
            fontWeight: "bold",
            whiteSpace: "nowrap",
            pointerEvents: "none",
            animation: "pulse 1.5s infinite"
          }}>
            ✋ Needs Input
          </div>
        </Html>
      )}
      
      {/* Error puff effect */}
      {state === "error" && (
        <mesh position={[0, 0.5, 0]}>
          <sphereGeometry args={[0.6, 16, 16]} />
          <meshBasicMaterial color="red" transparent opacity={0.4} />
        </mesh>
      )}
    </group>
  )
}

useGLTF.preload('/assets/character.glb')
