/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 packages/web/public/assets/assets/desk.glb -o packages/web/src/components/DeskModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['desk(Clone)']: THREE.Mesh
    Mesh_drawer: THREE.Mesh
    Mesh_drawer_1: THREE.Mesh
  }
  materials: {
    wood: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
  }
}

export function DeskModel(props: any) {
  const { nodes, materials } = useGLTF('/assets/desk.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['desk(Clone)'].geometry} material={materials.wood}>
        <group position={[0.04, 0.274, -0.164]}>
          <mesh geometry={nodes.Mesh_drawer.geometry} material={materials.wood} />
          <mesh geometry={nodes.Mesh_drawer_1.geometry} material={materials.metal} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/assets/desk.glb')
