/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 packages/web/public/assets/assets/laptop.glb -o packages/web/src/components/LaptopModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_laptop: THREE.Mesh
    Mesh_laptop_1: THREE.Mesh
    Mesh_laptop_2: THREE.Mesh
  }
  materials: {
    metalDark: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
    metalMedium: THREE.MeshStandardMaterial
  }
}

export function LaptopModel(props: any) {
  const { nodes, materials } = useGLTF('/assets/laptop.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.44}>
        <mesh geometry={nodes.Mesh_laptop.geometry} material={materials.metalDark} />
        <mesh geometry={nodes.Mesh_laptop_1.geometry} material={materials.metal} />
        <mesh geometry={nodes.Mesh_laptop_2.geometry} material={materials.metalMedium} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/laptop.glb')
